apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
  # se definir apenas port: 80 -> indica que o service vai ouvir na porta 80 e enviar para porta 80 do pod 
    - port: 80
      #targetPort: 80
      #node port pode ser de 30000 até 32767
      nodePort: 30000
  selector:
    app:  primeiro-pod