apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  ports:
  # se definir apenas port: 80 -> indica que o service vai ouvir na porta 80 e enviar para porta 80 do pod 
    - port: 80
      nodePort: 31000
  selector:
    app:  primeiro-pod