apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app:  segundo-pod
  ports:
  # se definir apenas port: 80 -> indica que o service vai ouvir na porta 80 e enviar para porta 80 do pod 
    - port: 8080
      targetPort:   80